version: 2
jobs:
  build:
    parallelism: 4
    working_directory: ~/circleci-sg
    resource_class: xlarge
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run:
          name: Versions
          command: 'uname -a;java -version;openssl version'
      - checkout
      - restore_cache:
          key: circleci-sg-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-sg-{{ checksum "pom.xml" }}
      - run:
          command: |
            set -x
            cd src/test/java         
            TESTFILES="$(circleci tests glob **/*Test*.java | circleci tests split --split-by=timings | tr -s '\n' ',')"
            echo "$TESTFILES"
            cd ~/circleci-sg
            mvn -Pcoverage verify -Dtest="$TESTFILES"
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: /.circleci-task-data
      - deploy:
          name: Maybe Sonar and Deploy
          command: |
            mvn deploy -DskipTests -s settings.xml
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mvn -Pcoverage sonar:sonar -Dsonar.organization=floragunncom-github -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=https://sonarcloud.io
            fi

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build